config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:create, :destroy]
  resources :images, except: [:new, :edit] do
    scope module: :image do
      resource :content, only: :show
      resources :tags, only: :create
    end
  end
  resources :tags
  root 'top#index'
end

app/models/account.rb
# Copyright (c) 2016 Ricoh Company, Ltd. All Rights Reserved.
# See LICENSE for more information

class Account < ActiveRecord::Base
  include Concerns::RicohId

  def refresh_session_if_expired!
    if ricoh_session.expired? && refresh_token.present?
      access_token = refresh_ricoh_session!
      update! access_token: access_token.access_token
    end
  end

  class << self
    def authenticate!(username, password)
      access_token = authenticate_ricoh_id username, password
      account = Account.where(identifier: access_token.subject).first_or_initialize
      account.ricoh_session = access_token
      account.save!
      account
    end
  end
end

app/models/concerns/ricoh_id.rb
# Copyright (c) 2016 Ricoh Company, Ltd. All Rights Reserved.
# See LICENSE for more information

module Concerns
  module RicohId
    extend ActiveSupport::Concern

    def ricoh_session
      @ricoh_access_token ||= RicohAPI::Auth::AccessToken.new access_token
    end

    def ricoh_session=(access_token)
      self.access_token, self.refresh_token = access_token.access_token, access_token.refresh_token
    end

    def refresh_ricoh_session!
      client = self.class.ricoh_oauth_client
      client.refresh_token = refresh_token
      client.api_token_for! RicohAPI::MStorage::SCOPE
    end

    module ClassMethods
      def ricoh_oauth_client
        RicohAPI::Auth::Client.new(
          Rails.application.secrets.ricoh_api['client_id'],
          Rails.application.secrets.ricoh_api['client_secret']
        )
      end

      def authenticate_ricoh_id(username, password)
        client = ricoh_oauth_client
        client.resource_owner_credentials = username, password
        client.api_token_for! RicohAPI::MStorage::SCOPE
      end
    end
  end
end

app/controllers/application_controller.rb
# Copyright (c) 2016 Ricoh Company, Ltd. All Rights Reserved.
# See LICENSE for more information

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include Concerns::Authentication
  include Concerns::Globalize
end

app/controllers/concerns/authentication.rb
# Copyright (c) 2016 Ricoh Company, Ltd. All Rights Reserved.
# See LICENSE for more information

module Concerns
  module Authentication
    extend ActiveSupport::Concern

    class AuthenticationRequired < StandardError; end
    class AnonymousAccessRequired < StandardError; end

    included do
      before_filter :optional_authentication
      helper_method :current_account, :authenticated?
      rescue_from AuthenticationRequired,  with: :authentication_required!
      rescue_from AnonymousAccessRequired, with: :anonymous_access_required!
    end

    def current_account
      @current_account
    end

    def authenticated?
      !current_account.blank?
    end

    def authentication_required!(e)
      redirect_to root_url, flash: {
        warning: e.message
      }
    end

    def anonymous_access_required!(e)
      redirect_to images_url
    end

    def optional_authentication
      if session[:current_account]
        authenticate Account.find_by_id(session[:current_account])
      end
    rescue ActiveRecord::RecordNotFound
      unauthenticate!
    end

    def require_authentication
      unless authenticated?
        session[:after_logged_in_endpoint] = request.url if request.get?
        raise AuthenticationRequired.new
      end
    end

    def require_anonymous_access
      raise AnonymousAccessRequired.new if authenticated?
    end

    def authenticate(account)
      if account
        @current_account = account
        session[:current_account] = account.id
      end
    end

    def unauthenticate!
      @current_account = session[:current_account] = nil
    end
  end
end

app/controllers/concerns/globalize.rb
# Copyright (c) 2016 Ricoh Company, Ltd. All Rights Reserved.
# See LICENSE for more information

module Concerns
  module Globalize
    extend ActiveSupport::Concern

    included do
      before_filter :set_locale
    end

    def set_locale
      accepted_languages = request.env['HTTP_ACCEPT_LANGUAGE']
      if accepted_languages.present?
        I18n.locale = accepted_languages.split(',').collect do |lang|
          lang[0, 2]
        end.detect do |locale|
          I18n.available_locales.include? locale.to_sym
        end
      end
    end
  end
end

app/controllers/concerns/ricoh_api_access.rb
# Copyright (c) 2016 Ricoh Company, Ltd. All Rights Reserved.
# See LICENSE for more information

module Concerns
  module RicohApiAccess
    extend ActiveSupport::Concern

    included do
      before_filter :require_authentication
      before_filter :refresh_session_if_expired!
      rescue_from(
        RicohAPI::MStorage::Client::Unauthorized,
        Rack::OAuth2::Client::Error,
        with: :require_re_login
      )
    end

    protected

    def storage_api_client
      @storage_client ||= RicohAPI::MStorage::Client.new(
        current_account.access_token
      )
    end

    private

    def require_re_login(e)
      flash[:warning] = e.message
      unauthenticate!
      redirect_to root_url
    end

    def refresh_session_if_expired!
      current_account.refresh_session_if_expired!
    end
  end
end

app/controllers/image/contents_controller.rb
# Copyright (c) 2016 Ricoh Company, Ltd. All Rights Reserved.
# See LICENSE for more information

class Image::ContentsController < ApplicationController
  include Concerns::RicohApiAccess

  def show
    data = storage_api_client.download(params[:image_id])
    send_data data, type: 'image/jpeg', disposition: 'inline'
  end
end

app/controllers/image/tags_controller.rb
# Copyright (c) 2016 Ricoh Company, Ltd. All Rights Reserved.
# See LICENSE for more information

class Image::TagsController < ApplicationController
  include Concerns::RicohApiAccess

  def create
    storage_api_client.tags_to params[:image_id], params[:tag]
    redirect_to image_url(params[:image_id])
  end
end

app/controllers/images_controller.rb
# Copyright (c) 2016 Ricoh Company, Ltd. All Rights Reserved.
# See LICENSE for more information

class ImagesController < ApplicationController
  include Concerns::RicohApiAccess

  def index
    @images = storage_api_client.list params
  end

  def show
    @image = storage_api_client.info params[:id]
    @image_meta = storage_api_client.meta params[:id]
    # @image_tags = storage_api_client.tags_on params[:id]
  end

  def create
    image = storage_api_client.upload content: params[:file].open
    redirect_to image_url(image[:id])
  end

  def destroy
    storage_api_client.delete params[:id]
    redirect_to images_url
  end
end

app/controllers/sessions_controller.rb
# Copyright (c) 2016 Ricoh Company, Ltd. All Rights Reserved.
# See LICENSE for more information

class SessionsController < ApplicationController
  def create
    account = Account.authenticate!(
      params[:username],
      params[:password]
    )
    authenticate account
    redirect_to images_url
  rescue => e
    # NOTE: for developers, showing any API errors. not for production use.
    authentication_required! e
  end

  def destroy
    unauthenticate!
    redirect_to root_url
  end
end

app/controllers/tags_controller.rb
# Copyright (c) 2016 Ricoh Company, Ltd. All Rights Reserved.
# See LICENSE for more information

class TagsController < ApplicationController
end

app/controllers/top_controller.rb
# Copyright (c) 2016 Ricoh Company, Ltd. All Rights Reserved.
# See LICENSE for more information

class TopController < ApplicationController
  before_filter :require_anonymous_access

  def index
  end
end

app/helpers/application_helper.rb
# Copyright (c) 2016 Ricoh Company, Ltd. All Rights Reserved.
# See LICENSE for more information

module ApplicationHelper
end

app/helpers/image/contents_helper.rb
# Copyright (c) 2016 Ricoh Company, Ltd. All Rights Reserved.
# See LICENSE for more information

module Image::ContentsHelper
end

app/helpers/image/tags_helper.rb
# Copyright (c) 2016 Ricoh Company, Ltd. All Rights Reserved.
# See LICENSE for more information

module Image::TagsHelper
end

app/helpers/images_helper.rb
# Copyright (c) 2016 Ricoh Company, Ltd. All Rights Reserved.
# See LICENSE for more information

module ImagesHelper
end

app/helpers/tags_helper.rb
# Copyright (c) 2016 Ricoh Company, Ltd. All Rights Reserved.
# See LICENSE for more information

module TagsHelper
end

app/helpers/top_helper.rb
# Copyright (c) 2016 Ricoh Company, Ltd. All Rights Reserved.
# See LICENSE for more information

module TopHelper
end

app/views/images/_tagging_form.html.erb
<div class="bs-component"%>
  <%= form_tag image_tags_path(@image[:id]), id: 'tagging_form' do %>
    <fieldset class="form-horizontal">
      <div class="form-group label-static is-fileinput">
        <%= label_tag :tag, 'tagging_form.label.tag'.t, class: 'col-md-4 control-label' %>
        <div class="col-md-8">
          <%= text_field_tag :tag, params[:tag], class: 'form-control', placeholder: 'tagging_form.placeholder.tag'.t %>
        </div>
      </div>
      <nav>
        <%= submit_tag 'tagging_form.label.submit'.t, class: 'btn btn-primary' %>
      </nav>
    </fieldset>
  <% end %>
</div>

app/views/images/_upload_form.html.erb
<div class="bs-component"%>
  <%= form_tag images_path, id: 'upload_form', multipart: true do %>
    <fieldset class="form-horizontal">
      <div class="form-group label-static is-fileinput">
        <%= label_tag :file, 'upload_form.label.file'.t, class: 'col-md-4 control-label' %>
        <div class="col-md-8">
          <%= file_field_tag :file, class: 'form-control', placeholder: 'upload_form.placeholder.file'.t %>
        </div>
      </div>
      <nav>
        <%= submit_tag 'upload_form.label.submit'.t, class: 'btn btn-primary' %>
      </nav>
    </fieldset>
  <% end %>
</div>

app/views/images/index.html.erb
<section class="bs-docs-section">
  <div class="row">
    <div class="col-md-12">
      <div class="bs-component">
        <h3><%= 'images.index.heading'.t %></h3>
      </div>
    </div>
  </div>
</section>

<section class="bs-docs-section">
  <% @images[:media].each_slice(3) do |media| %>
    <div class="row">
      <% media.each do |file| %>
        <div class="col-md-4">
          <%= link_to image_tag(image_content_path(file[:id]), class: 'thumbnail'), image_path(file[:id]) %>
        </div>
      <% end %>
    </div>
  <% end %>
</section>

<section class="bs-docs-section">
  <div class="row">
    <div class="col-md-6">
    </div>
    <div class="col-md-6">
      <%= render 'images/upload_form' %>
    </div>
  </div>
</section>

app/views/images/show.html.erb
<section class="bs-docs-section">
  <div class="row">
    <div class="col-md-12">
      <div class="bs-component">
        <h2><%= 'images.show.heading'.t %></h2>
        <p class="lead"><%= 'images.show.description'.t %></p>
      </div>
    </div>
  </div>
</section>

<section class="bs-docs-section">
  <div class="row">
    <div class="col-md-8">
      <%= image_tag image_content_path(@image[:id]) %>
    </div>
    <div class="col-md-4">
      <pre><%= JSON.pretty_generate @image_meta %></pre>
<%
=begin
%>
      <ul>
        <% @image_tags[:tags].each do |tag| %>
          <li>#TAG</li>
        <% end %>
      </ul>
      <%= render 'images/tagging_form' %>
<%
=end
%>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= link_to image_path(@image[:id]), method: :delete do %>
        <%= 'images.show.delete'.t %>
        <%= material_icon.delete %>
      <% end %>
    </div>
  </div>
</section>

app/views/layouts/_flash.html.erb
<section class="bs-docs-section">
  <div class="row">
    <div class="col-md-12">
      <% [:warning, :danger, :success, :info].each do |message_type| %>
        <% if flash[message_type].present? %>
          <div class="bs-component fade-out-automatically">
            <div class="alert alert-dismissible alert-<%= message_type %>">
              <button type="button" class="close" data-dismiss="alert">×</button>
              <p><%= flash[message_type] %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</section>

app/views/layouts/_footer.html.erb
<div class="page-footer">
  <p>&copy; <%= 'site.copyright'.t %></p>
</div>

app/views/layouts/_header.html.erb
<section class="bs-docs-section">
  <div class="row">
    <div class="col-md-12">
      <div class="page-header">
      </div>
    </div>
  </div>
</section>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button class="navbar-toggle" data-target=".navbar-responsive-collapse" data-toggle="collapse" type="button">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'site.title'.t, root_path, class: 'navbar-brand' %>
    </div>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if authenticated? %>
          <li>
            <%= link_to session_path, method: :delete do %>
              <%= 'navi.logout'.t %>
              <%= material_icon.exit_to_app %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= 'site.title'.t %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon.png">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<%= content_tag :body, class: controller_name do %>
  <%= render 'layouts/navigation' %>
  <div class="container">
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash' %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  <%= yield :bottom %>
  <script>
    $(function () {
      $.material.init();
    });
  </script>
<% end %>
</html>

app/views/top/_login_form.html.erb
<div class="well bs-component"%>
  <%= form_tag session_path, id: 'login_form' do %>
    <fieldset class="form-horizontal">
      <div class="form-group label-static">
        <%= label_tag :username, 'login_form.label.username'.t, class: 'col-md-4 control-label' %>
        <div class="col-md-8">
          <%= text_field_tag :username, params[:username], class: 'form-control', placeholder: 'login_form.placeholder.username'.t %>
        </div>
      </div>

      <div class="form-group label-static">
        <%= label_tag :password, 'login_form.label.password'.t, class: 'col-md-4 control-label' %>
        <div class="col-md-8">
          <%= password_field_tag :password, params[:password], class: 'form-control', placeholder: 'login_form.placeholder.password'.t %>
        </div>
      </div>

      <nav>
        <%= submit_tag 'login_form.label.submit'.t, class: 'btn btn-primary' %>
      </nav>
    </fieldset>
  <% end %>
</div>

app/views/top/index.html.erb
<section class="bs-docs-section">
  <div class="row">
    <div class="col-md-6">
      <div class="bs-component">
        <h2><%= 'top.heading'.t %></h2>
        <p class="lead"><%= 'top.description'.t %></p>
      </div>
    </div>
    <div class="col-md-6">
      <%= render 'top/login_form' %>
    </div>
  </div>
</section>